# Generated by Django 4.1.3 on 2022-12-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='help_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
