# Generated by Django 4.0.4 on 2022-12-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0002_alter_annotation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='user',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
