from .spaceform import SpaceModelForm
from .create_space import CreateSpaceModelForm
from .create_message import CreateMessageModelForm
from .create_step import CreateStepModelForm
from .update_space import UpdateSpaceModelForm
from .edit_profile import EditProfileForm
from .create_content import CreateContentForm
from .create_term import CreateTermModelForm
from .resource import ResourceModelForm
from .update_resource import UpdateResourceModelForm
from  .edit_profile1 import EditProfile1Form