# Generated by Django 4.1.3 on 2022-12-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationmodel',
            name='annotation_id',
            field=models.CharField(default='defaultvalue', max_length=200),
            preserve_default=False,
        ),
    ]
