# Generated by Django 4.1.3 on 2022-12-17 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_annotationmodel_annotation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationmodel',
            name='annotation_id',
        ),
        migrations.RemoveField(
            model_name='annotationmodel',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='annotationmodel',
            name='uri',
        ),
    ]
