import imp
from .homepage import homepage
from .aboutus import aboutus
from .spaces import spaces
from .mycreatedspaces import mycreatedspaces
from .mymemberspaces import mymemberspaces
from .spacedetails import spacedetails
from .create_space import create_space
from .create_message import create_message
from .create_term import create_term
from .create_step import create_step
from .warning import warning
from .update_space import update_space
from .delete_space import delete_space
from .signout import signout
from .change_password import change_password
from .edit_profile import edit_profile
from .register import register
from .create_content import create_content
from .content_relations import content_relations
from .display_contents import display_contents
from .delete_content import delete_content
from .resource import resource
from .update_resource import update_resource
from .delete_resource import delete_resource
from .display_resource import display_resource
from .display_step import display_step
from .display_members import display_members
from .edit_profile1 import edit_profile1
from .quiz_section import quiz_section
from .resources_section import resource_section
from .discussion_section import discussion_section
from .learning_steps import learning_section
from .glossary_section import glossary_section
from .graph_section import graph_section
