# Generated by Django 4.0.4 on 2022-11-28 15:09

import autoslug.fields
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('link', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpaceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdSpaces', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('members', models.ManyToManyField(related_name='includedSpaces', to=settings.AUTH_USER_MODEL, verbose_name='members')),
            ],
            options={
                'verbose_name': 'Space',
                'verbose_name_plural': 'Spaces',
                'db_table': 'space',
            },
        ),
        migrations.CreateModel(
            name='TermModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termtitle', models.CharField(max_length=50)),
                ('termdefinition', ckeditor.fields.RichTextField(max_length=500)),
                ('termstep', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('termspace', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='space.spacemodel')),
                ('termwriter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terms',
                'db_table': 'term_table',
            },
        ),
        migrations.CreateModel(
            name='StepModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steptitle', models.CharField(max_length=50)),
                ('stepcontent', ckeditor.fields.RichTextField(max_length=500)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='files')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('stepcreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step', to=settings.AUTH_USER_MODEL)),
                ('stepspace', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='space.spacemodel')),
            ],
            options={
                'verbose_name': 'Steps',
                'verbose_name_plural': 'Steps',
                'db_table': 'step_table',
            },
        ),
        migrations.CreateModel(
            name='RelationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_content', to='space.contentmodel')),
                ('space', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='space.spacemodel')),
                ('target_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_content', to='space.contentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('memberspace', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='space.spacemodel')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'message_table',
            },
        ),
        migrations.AddField(
            model_name='contentmodel',
            name='space',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='space.spacemodel'),
        ),
    ]
