# Generated by Django 4.1.3 on 2022-12-06 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_remove_stepmodel_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepmodel',
            name='relatedresource',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='stepresource', to='space.resourcemodel'),
        ),
    ]
