# Generated by Django 4.1.3 on 2022-12-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0006_spacemodel_tag1_spacemodel_tag2_spacemodel_tag3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacemodel',
            name='searchwords',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
